### PR TITLE
Revert "Create LICENSE"

### PR DESCRIPTION
**Pull request by MuhireIghor**
Reverts claranceliberi/instafoot#1

### CODE REVIEW

**Comment by MuhireIghor** [comment]
--

**Comment by claranceliberi** [comment]
Why? reverting the license?

**Comment by MuhireIghor** [comment]
Hey,I am sorry for the reversion It happened by accident

**Comment by claranceliberi** [comment]
> Hey,I am sorry for the reversion It happened by accident


No there is no reason to apologize

**Pull request closed without merging**
